USE Demo
GO
--01.One-To-One Relationship
CREATE TABLE Passports(
PassportID INT PRIMARY KEY NOT NULL,
PassportNumber NVARCHAR(50) NOT NULL
)

CREATE TABLE Persons(
PersonID INT PRIMARY KEY NOT NULL,
FirstName NVARCHAR(50) NOT NULL,
Salary DECIMAL NOT NULL,
PassportID INT NOT NULL
)

INSERT INTO Passports VALUES 
(101, 'N34FG21B'), 
(102, 'K65LO4R7'), 
(103, 'ZE657QP2')

INSERT INTO Persons VALUES 
(1, 'Roberto', 43330.00, 102),
(2, 'Tom', 56100.00, 103),
(3, 'Yana', 60200.00, 101)

ALTER TABLE Persons
ADD CONSTRAINT FK_Persons_Passports FOREIGN KEY (PassportID) REFERENCES Passports(PassportID)
